//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 10:54:55 PM CEST 
//


package osis;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for calendar.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="calendar">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Chinese"/>
 *     &lt;enumeration value="Gregorian"/>
 *     &lt;enumeration value="Islamic"/>
 *     &lt;enumeration value="ISO"/>
 *     &lt;enumeration value="Jewish"/>
 *     &lt;enumeration value="Julian"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "calendar")
@XmlEnum
public enum Calendar {

    @XmlEnumValue("Chinese")
    CHINESE("Chinese"),
    @XmlEnumValue("Gregorian")
    GREGORIAN("Gregorian"),
    @XmlEnumValue("Islamic")
    ISLAMIC("Islamic"),
    ISO("ISO"),
    @XmlEnumValue("Jewish")
    JEWISH("Jewish"),
    @XmlEnumValue("Julian")
    JULIAN("Julian");
    private final String value;

    Calendar(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Calendar fromValue(String v) {
        for (Calendar c: Calendar.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
