//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 10:54:55 PM CEST 
//


package osis;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for osisTextCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="osisTextCT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}headerCT"/>
 *         &lt;element name="titlePage" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}titlePageCT" minOccurs="0"/>
 *         &lt;element name="div" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}divCT" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="annotateRef" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}annotateRefType" />
 *       &lt;attribute name="canonical" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="osisID" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}osisIDType" />
 *       &lt;attribute name="osisIDWork" use="required" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}osisWorkType" />
 *       &lt;attribute name="osisRefWork" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}osisWorkType" default="Bible" />
 *       &lt;attribute name="type" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}attributeExtension" />
 *       &lt;attribute name="subType" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}attributeExtension" />
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang use="required""/>
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}space default="default""/>
 *       &lt;attribute name="TEIform" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="text" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "osisTextCT", propOrder = {
    "header",
    "titlePage",
    "div"
})
public class OsisTextCT {

    @XmlElement(required = true)
    protected HeaderCT header;
    protected TitlePageCT titlePage;
    protected List<DivCT> div;
    @XmlAttribute
    protected List<String> annotateRef;
    @XmlAttribute
    protected Boolean canonical;
    @XmlAttribute(name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute
    protected List<String> osisID;
    @XmlAttribute(required = true)
    protected String osisIDWork;
    @XmlAttribute
    protected String osisRefWork;
    @XmlAttribute
    protected String type;
    @XmlAttribute
    protected String subType;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace", required = true)
    protected String lang;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String space;
    @XmlAttribute(name = "TEIform")
    @XmlSchemaType(name = "anySimpleType")
    protected String teIform;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderCT }
     *     
     */
    public HeaderCT getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderCT }
     *     
     */
    public void setHeader(HeaderCT value) {
        this.header = value;
    }

    /**
     * Gets the value of the titlePage property.
     * 
     * @return
     *     possible object is
     *     {@link TitlePageCT }
     *     
     */
    public TitlePageCT getTitlePage() {
        return titlePage;
    }

    /**
     * Sets the value of the titlePage property.
     * 
     * @param value
     *     allowed object is
     *     {@link TitlePageCT }
     *     
     */
    public void setTitlePage(TitlePageCT value) {
        this.titlePage = value;
    }

    /**
     * Gets the value of the div property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the div property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiv().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DivCT }
     * 
     * 
     */
    public List<DivCT> getDiv() {
        if (div == null) {
            div = new ArrayList<DivCT>();
        }
        return this.div;
    }

    /**
     * Gets the value of the annotateRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotateRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotateRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAnnotateRef() {
        if (annotateRef == null) {
            annotateRef = new ArrayList<String>();
        }
        return this.annotateRef;
    }

    /**
     * Gets the value of the canonical property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isCanonical() {
        if (canonical == null) {
            return true;
        } else {
            return canonical;
        }
    }

    /**
     * Sets the value of the canonical property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCanonical(Boolean value) {
        this.canonical = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the osisID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the osisID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOsisID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOsisID() {
        if (osisID == null) {
            osisID = new ArrayList<String>();
        }
        return this.osisID;
    }

    /**
     * Gets the value of the osisIDWork property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOsisIDWork() {
        return osisIDWork;
    }

    /**
     * Sets the value of the osisIDWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOsisIDWork(String value) {
        this.osisIDWork = value;
    }

    /**
     * Gets the value of the osisRefWork property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOsisRefWork() {
        if (osisRefWork == null) {
            return "Bible";
        } else {
            return osisRefWork;
        }
    }

    /**
     * Sets the value of the osisRefWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOsisRefWork(String value) {
        this.osisRefWork = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the subType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubType() {
        return subType;
    }

    /**
     * Sets the value of the subType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubType(String value) {
        this.subType = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        if (space == null) {
            return "default";
        } else {
            return space;
        }
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }

    /**
     * Gets the value of the teIform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEIform() {
        if (teIform == null) {
            return "text";
        } else {
            return teIform;
        }
    }

    /**
     * Sets the value of the teIform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEIform(String value) {
        this.teIform = value;
    }

}
