//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 10:54:55 PM CEST 
//


package osis;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for osisChanges.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="osisChanges">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="added"/>
 *     &lt;enumeration value="amplified"/>
 *     &lt;enumeration value="changed"/>
 *     &lt;enumeration value="deleted"/>
 *     &lt;enumeration value="implied"/>
 *     &lt;enumeration value="moved"/>
 *     &lt;enumeration value="tenseChange"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "osisChanges")
@XmlEnum
public enum OsisChanges {

    @XmlEnumValue("added")
    ADDED("added"),
    @XmlEnumValue("amplified")
    AMPLIFIED("amplified"),
    @XmlEnumValue("changed")
    CHANGED("changed"),
    @XmlEnumValue("deleted")
    DELETED("deleted"),
    @XmlEnumValue("implied")
    IMPLIED("implied"),
    @XmlEnumValue("moved")
    MOVED("moved"),
    @XmlEnumValue("tenseChange")
    TENSE_CHANGE("tenseChange");
    private final String value;

    OsisChanges(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OsisChanges fromValue(String v) {
        for (OsisChanges c: OsisChanges.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
