//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 10:54:55 PM CEST 
//


package osis;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for osisSegs.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="osisSegs">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="alluded"/>
 *     &lt;enumeration value="keyword"/>
 *     &lt;enumeration value="otPassage"/>
 *     &lt;enumeration value="verseNumber"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "osisSegs")
@XmlEnum
public enum OsisSegs {

    @XmlEnumValue("alluded")
    ALLUDED("alluded"),
    @XmlEnumValue("keyword")
    KEYWORD("keyword"),
    @XmlEnumValue("otPassage")
    OT_PASSAGE("otPassage"),
    @XmlEnumValue("verseNumber")
    VERSE_NUMBER("verseNumber");
    private final String value;

    OsisSegs(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OsisSegs fromValue(String v) {
        for (OsisSegs c: OsisSegs.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
