//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 10:54:55 PM CEST 
//


package osis;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for osisPlacementNote.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="osisPlacementNote">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="foot"/>
 *     &lt;enumeration value="end"/>
 *     &lt;enumeration value="inline"/>
 *     &lt;enumeration value="left"/>
 *     &lt;enumeration value="right"/>
 *     &lt;enumeration value="interlinear"/>
 *     &lt;enumeration value="apparatus"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "osisPlacementNote")
@XmlEnum
public enum OsisPlacementNote {

    @XmlEnumValue("foot")
    FOOT("foot"),
    @XmlEnumValue("end")
    END("end"),
    @XmlEnumValue("inline")
    INLINE("inline"),
    @XmlEnumValue("left")
    LEFT("left"),
    @XmlEnumValue("right")
    RIGHT("right"),
    @XmlEnumValue("interlinear")
    INTERLINEAR("interlinear"),
    @XmlEnumValue("apparatus")
    APPARATUS("apparatus");
    private final String value;

    OsisPlacementNote(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OsisPlacementNote fromValue(String v) {
        for (OsisPlacementNote c: OsisPlacementNote.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
