//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 10:54:55 PM CEST 
//


package osis;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for osisLine.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="osisLine">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="refrain"/>
 *     &lt;enumeration value="doxology"/>
 *     &lt;enumeration value="selah"/>
 *     &lt;enumeration value="attribution"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "osisLine")
@XmlEnum
public enum OsisLine {

    @XmlEnumValue("refrain")
    REFRAIN("refrain"),
    @XmlEnumValue("doxology")
    DOXOLOGY("doxology"),
    @XmlEnumValue("selah")
    SELAH("selah"),
    @XmlEnumValue("attribution")
    ATTRIBUTION("attribution");
    private final String value;

    OsisLine(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OsisLine fromValue(String v) {
        for (OsisLine c: OsisLine.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
