//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 10:54:55 PM CEST 
//


package osis;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for osisIdentifier.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="osisIdentifier">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Dewey"/>
 *     &lt;enumeration value="DOI"/>
 *     &lt;enumeration value="ISBN"/>
 *     &lt;enumeration value="ISSN"/>
 *     &lt;enumeration value="LCCN"/>
 *     &lt;enumeration value="OSIS"/>
 *     &lt;enumeration value="SICI"/>
 *     &lt;enumeration value="URI"/>
 *     &lt;enumeration value="URL"/>
 *     &lt;enumeration value="URN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "osisIdentifier")
@XmlEnum
public enum OsisIdentifier {

    @XmlEnumValue("Dewey")
    DEWEY("Dewey"),
    DOI("DOI"),
    ISBN("ISBN"),
    ISSN("ISSN"),
    LCCN("LCCN"),
    OSIS("OSIS"),
    SICI("SICI"),
    URI("URI"),
    URL("URL"),
    URN("URN");
    private final String value;

    OsisIdentifier(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OsisIdentifier fromValue(String v) {
        for (OsisIdentifier c: OsisIdentifier.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
