//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 10:54:55 PM CEST 
//


package osis;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for osisLanguageUsage.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="osisLanguageUsage">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="base"/>
 *     &lt;enumeration value="didactic"/>
 *     &lt;enumeration value="interlinear"/>
 *     &lt;enumeration value="original"/>
 *     &lt;enumeration value="quotation"/>
 *     &lt;enumeration value="source"/>
 *     &lt;enumeration value="target"/>
 *     &lt;enumeration value="translation"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "osisLanguageUsage")
@XmlEnum
public enum OsisLanguageUsage {

    @XmlEnumValue("base")
    BASE("base"),
    @XmlEnumValue("didactic")
    DIDACTIC("didactic"),
    @XmlEnumValue("interlinear")
    INTERLINEAR("interlinear"),
    @XmlEnumValue("original")
    ORIGINAL("original"),
    @XmlEnumValue("quotation")
    QUOTATION("quotation"),
    @XmlEnumValue("source")
    SOURCE("source"),
    @XmlEnumValue("target")
    TARGET("target"),
    @XmlEnumValue("translation")
    TRANSLATION("translation");
    private final String value;

    OsisLanguageUsage(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OsisLanguageUsage fromValue(String v) {
        for (OsisLanguageUsage c: OsisLanguageUsage.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
