//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 10:54:55 PM CEST 
//


package osis;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for osisDivs.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="osisDivs">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="acknowledgement"/>
 *     &lt;enumeration value="afterword"/>
 *     &lt;enumeration value="annotant"/>
 *     &lt;enumeration value="appendix"/>
 *     &lt;enumeration value="article"/>
 *     &lt;enumeration value="back"/>
 *     &lt;enumeration value="bibliography"/>
 *     &lt;enumeration value="body"/>
 *     &lt;enumeration value="book"/>
 *     &lt;enumeration value="bookGroup"/>
 *     &lt;enumeration value="bridge"/>
 *     &lt;enumeration value="chapter"/>
 *     &lt;enumeration value="colophon"/>
 *     &lt;enumeration value="commentary"/>
 *     &lt;enumeration value="concordance"/>
 *     &lt;enumeration value="coverPage"/>
 *     &lt;enumeration value="dedication"/>
 *     &lt;enumeration value="devotional"/>
 *     &lt;enumeration value="entry"/>
 *     &lt;enumeration value="front"/>
 *     &lt;enumeration value="gazetteer"/>
 *     &lt;enumeration value="glossary"/>
 *     &lt;enumeration value="imprimatur"/>
 *     &lt;enumeration value="index"/>
 *     &lt;enumeration value="introduction"/>
 *     &lt;enumeration value="majorSection"/>
 *     &lt;enumeration value="map"/>
 *     &lt;enumeration value="outline"/>
 *     &lt;enumeration value="paragraph"/>
 *     &lt;enumeration value="part"/>
 *     &lt;enumeration value="preface"/>
 *     &lt;enumeration value="publicationData"/>
 *     &lt;enumeration value="section"/>
 *     &lt;enumeration value="subSection"/>
 *     &lt;enumeration value="summary"/>
 *     &lt;enumeration value="tableofContents"/>
 *     &lt;enumeration value="titlePage"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "osisDivs")
@XmlEnum
public enum OsisDivs {

    @XmlEnumValue("acknowledgement")
    ACKNOWLEDGEMENT("acknowledgement"),
    @XmlEnumValue("afterword")
    AFTERWORD("afterword"),
    @XmlEnumValue("annotant")
    ANNOTANT("annotant"),
    @XmlEnumValue("appendix")
    APPENDIX("appendix"),
    @XmlEnumValue("article")
    ARTICLE("article"),
    @XmlEnumValue("back")
    BACK("back"),
    @XmlEnumValue("bibliography")
    BIBLIOGRAPHY("bibliography"),
    @XmlEnumValue("body")
    BODY("body"),
    @XmlEnumValue("book")
    BOOK("book"),
    @XmlEnumValue("bookGroup")
    BOOK_GROUP("bookGroup"),
    @XmlEnumValue("bridge")
    BRIDGE("bridge"),
    @XmlEnumValue("chapter")
    CHAPTER("chapter"),
    @XmlEnumValue("colophon")
    COLOPHON("colophon"),
    @XmlEnumValue("commentary")
    COMMENTARY("commentary"),
    @XmlEnumValue("concordance")
    CONCORDANCE("concordance"),
    @XmlEnumValue("coverPage")
    COVER_PAGE("coverPage"),
    @XmlEnumValue("dedication")
    DEDICATION("dedication"),
    @XmlEnumValue("devotional")
    DEVOTIONAL("devotional"),
    @XmlEnumValue("entry")
    ENTRY("entry"),
    @XmlEnumValue("front")
    FRONT("front"),
    @XmlEnumValue("gazetteer")
    GAZETTEER("gazetteer"),
    @XmlEnumValue("glossary")
    GLOSSARY("glossary"),
    @XmlEnumValue("imprimatur")
    IMPRIMATUR("imprimatur"),
    @XmlEnumValue("index")
    INDEX("index"),
    @XmlEnumValue("introduction")
    INTRODUCTION("introduction"),
    @XmlEnumValue("majorSection")
    MAJOR_SECTION("majorSection"),
    @XmlEnumValue("map")
    MAP("map"),
    @XmlEnumValue("outline")
    OUTLINE("outline"),
    @XmlEnumValue("paragraph")
    PARAGRAPH("paragraph"),
    @XmlEnumValue("part")
    PART("part"),
    @XmlEnumValue("preface")
    PREFACE("preface"),
    @XmlEnumValue("publicationData")
    PUBLICATION_DATA("publicationData"),
    @XmlEnumValue("section")
    SECTION("section"),
    @XmlEnumValue("subSection")
    SUB_SECTION("subSection"),
    @XmlEnumValue("summary")
    SUMMARY("summary"),
    @XmlEnumValue("tableofContents")
    TABLEOF_CONTENTS("tableofContents"),
    @XmlEnumValue("titlePage")
    TITLE_PAGE("titlePage");
    private final String value;

    OsisDivs(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OsisDivs fromValue(String v) {
        for (OsisDivs c: OsisDivs.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
