//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 10:54:55 PM CEST 
//


package osis;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for osisCorpusCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="osisCorpusCT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}corpusHeaderCT" minOccurs="0"/>
 *         &lt;element name="titlePage" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}titlePageCT" minOccurs="0"/>
 *         &lt;element name="osisText" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}osisTextCT" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="TEIform" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="teiCorpus.2" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "osisCorpusCT", propOrder = {
    "header",
    "titlePage",
    "osisText"
})
public class OsisCorpusCT {

    protected CorpusHeaderCT header;
    protected TitlePageCT titlePage;
    @XmlElement(required = true)
    protected List<OsisTextCT> osisText;
    @XmlAttribute(name = "TEIform")
    @XmlSchemaType(name = "anySimpleType")
    protected String teIform;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link CorpusHeaderCT }
     *     
     */
    public CorpusHeaderCT getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorpusHeaderCT }
     *     
     */
    public void setHeader(CorpusHeaderCT value) {
        this.header = value;
    }

    /**
     * Gets the value of the titlePage property.
     * 
     * @return
     *     possible object is
     *     {@link TitlePageCT }
     *     
     */
    public TitlePageCT getTitlePage() {
        return titlePage;
    }

    /**
     * Sets the value of the titlePage property.
     * 
     * @param value
     *     allowed object is
     *     {@link TitlePageCT }
     *     
     */
    public void setTitlePage(TitlePageCT value) {
        this.titlePage = value;
    }

    /**
     * Gets the value of the osisText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the osisText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOsisText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OsisTextCT }
     * 
     * 
     */
    public List<OsisTextCT> getOsisText() {
        if (osisText == null) {
            osisText = new ArrayList<OsisTextCT>();
        }
        return this.osisText;
    }

    /**
     * Gets the value of the teIform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEIform() {
        if (teIform == null) {
            return "teiCorpus.2";
        } else {
            return teIform;
        }
    }

    /**
     * Sets the value of the teIform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEIform(String value) {
        this.teIform = value;
    }

}
