//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 10:54:55 PM CEST 
//


package osis;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for osisPlacementTitle.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="osisPlacementTitle">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="leftHead"/>
 *     &lt;enumeration value="centerHead"/>
 *     &lt;enumeration value="rightHead"/>
 *     &lt;enumeration value="insideHead"/>
 *     &lt;enumeration value="outsideHead"/>
 *     &lt;enumeration value="leftFoot"/>
 *     &lt;enumeration value="centerFoot"/>
 *     &lt;enumeration value="rightFoot"/>
 *     &lt;enumeration value="insideFoot"/>
 *     &lt;enumeration value="outsideFoot"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "osisPlacementTitle")
@XmlEnum
public enum OsisPlacementTitle {

    @XmlEnumValue("leftHead")
    LEFT_HEAD("leftHead"),
    @XmlEnumValue("centerHead")
    CENTER_HEAD("centerHead"),
    @XmlEnumValue("rightHead")
    RIGHT_HEAD("rightHead"),
    @XmlEnumValue("insideHead")
    INSIDE_HEAD("insideHead"),
    @XmlEnumValue("outsideHead")
    OUTSIDE_HEAD("outsideHead"),
    @XmlEnumValue("leftFoot")
    LEFT_FOOT("leftFoot"),
    @XmlEnumValue("centerFoot")
    CENTER_FOOT("centerFoot"),
    @XmlEnumValue("rightFoot")
    RIGHT_FOOT("rightFoot"),
    @XmlEnumValue("insideFoot")
    INSIDE_FOOT("insideFoot"),
    @XmlEnumValue("outsideFoot")
    OUTSIDE_FOOT("outsideFoot");
    private final String value;

    OsisPlacementTitle(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OsisPlacementTitle fromValue(String v) {
        for (OsisPlacementTitle c: OsisPlacementTitle.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
