//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 10:54:55 PM CEST 
//


package osis;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for osisReferences.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="osisReferences">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="annotateRef"/>
 *     &lt;enumeration value="parallel"/>
 *     &lt;enumeration value="source"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "osisReferences")
@XmlEnum
public enum OsisReferences {

    @XmlEnumValue("annotateRef")
    ANNOTATE_REF("annotateRef"),
    @XmlEnumValue("parallel")
    PARALLEL("parallel"),
    @XmlEnumValue("source")
    SOURCE("source");
    private final String value;

    OsisReferences(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OsisReferences fromValue(String v) {
        for (OsisReferences c: OsisReferences.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
