//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 10:54:55 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bibletechnologies.net/2003/OSIS/namespace", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package osis;
