//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 10:54:55 PM CEST 
//


package osis;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for workCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="workCT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}titleCT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="contributor" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}contributorCT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="creator" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}creatorCT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="subject" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}subjectCT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="date" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}dateCT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}descriptionCT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="publisher" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}publisherCT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}typeCT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="format" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}formatCT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="identifier" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}identifierCT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="source" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}sourceCT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="language" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}languageCT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="relation" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}relationCT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="coverage" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}coverageCT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="rights" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}rightsCT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="scope" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}scopeCT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="castList" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}castListCT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="teiHeader" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}teiHeaderCT" minOccurs="0"/>
 *         &lt;element name="refSystem" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}refSystemCT" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.bibletechnologies.net/2003/OSIS/namespace}globalWithType"/>
 *       &lt;attribute name="osisWork" use="required" type="{http://www.bibletechnologies.net/2003/OSIS/namespace}osisWorkType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "workCT", propOrder = {
    "title",
    "contributor",
    "creator",
    "subject",
    "date",
    "description",
    "publisher",
    "type",
    "format",
    "identifier",
    "source",
    "language",
    "relation",
    "coverage",
    "rights",
    "scope",
    "castList",
    "teiHeader",
    "refSystem"
})
public class WorkCT {

    protected List<TitleCT> title;
    protected List<ContributorCT> contributor;
    protected List<CreatorCT> creator;
    protected List<SubjectCT> subject;
    protected List<DateCT> date;
    protected List<DescriptionCT> description;
    protected List<PublisherCT> publisher;
    protected List<TypeCT> type;
    protected List<FormatCT> format;
    protected List<IdentifierCT> identifier;
    protected List<SourceCT> source;
    protected List<LanguageCT> language;
    protected List<RelationCT> relation;
    protected List<CoverageCT> coverage;
    protected List<RightsCT> rights;
    protected List<ScopeCT> scope;
    protected List<CastListCT> castList;
    protected TeiHeaderCT teiHeader;
    protected List<RefSystemCT> refSystem;
    @XmlAttribute(required = true)
    protected String osisWork;
    @XmlAttribute
    protected List<String> annotateRef;
    @XmlAttribute
    protected String annotateWork;
    @XmlAttribute
    protected String annotateType;
    @XmlAttribute
    @XmlSchemaType(name = "NMTOKENS")
    protected List<String> editions;
    @XmlAttribute(name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute
    protected List<String> osisID;
    @XmlAttribute
    protected String resp;
    @XmlAttribute
    protected String subType;
    @XmlAttribute
    protected String n;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String space;
    @XmlAttribute
    protected String script;

    /**
     * Gets the value of the title property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the title property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TitleCT }
     * 
     * 
     */
    public List<TitleCT> getTitle() {
        if (title == null) {
            title = new ArrayList<TitleCT>();
        }
        return this.title;
    }

    /**
     * Gets the value of the contributor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contributor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContributor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContributorCT }
     * 
     * 
     */
    public List<ContributorCT> getContributor() {
        if (contributor == null) {
            contributor = new ArrayList<ContributorCT>();
        }
        return this.contributor;
    }

    /**
     * Gets the value of the creator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreatorCT }
     * 
     * 
     */
    public List<CreatorCT> getCreator() {
        if (creator == null) {
            creator = new ArrayList<CreatorCT>();
        }
        return this.creator;
    }

    /**
     * Gets the value of the subject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubjectCT }
     * 
     * 
     */
    public List<SubjectCT> getSubject() {
        if (subject == null) {
            subject = new ArrayList<SubjectCT>();
        }
        return this.subject;
    }

    /**
     * Gets the value of the date property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the date property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateCT }
     * 
     * 
     */
    public List<DateCT> getDate() {
        if (date == null) {
            date = new ArrayList<DateCT>();
        }
        return this.date;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionCT }
     * 
     * 
     */
    public List<DescriptionCT> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionCT>();
        }
        return this.description;
    }

    /**
     * Gets the value of the publisher property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publisher property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublisher().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PublisherCT }
     * 
     * 
     */
    public List<PublisherCT> getPublisher() {
        if (publisher == null) {
            publisher = new ArrayList<PublisherCT>();
        }
        return this.publisher;
    }

    /**
     * Gets the value of the type property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the type property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeCT }
     * 
     * 
     */
    public List<TypeCT> getType() {
        if (type == null) {
            type = new ArrayList<TypeCT>();
        }
        return this.type;
    }

    /**
     * Gets the value of the format property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the format property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormatCT }
     * 
     * 
     */
    public List<FormatCT> getFormat() {
        if (format == null) {
            format = new ArrayList<FormatCT>();
        }
        return this.format;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifierCT }
     * 
     * 
     */
    public List<IdentifierCT> getIdentifier() {
        if (identifier == null) {
            identifier = new ArrayList<IdentifierCT>();
        }
        return this.identifier;
    }

    /**
     * Gets the value of the source property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the source property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SourceCT }
     * 
     * 
     */
    public List<SourceCT> getSource() {
        if (source == null) {
            source = new ArrayList<SourceCT>();
        }
        return this.source;
    }

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LanguageCT }
     * 
     * 
     */
    public List<LanguageCT> getLanguage() {
        if (language == null) {
            language = new ArrayList<LanguageCT>();
        }
        return this.language;
    }

    /**
     * Gets the value of the relation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelationCT }
     * 
     * 
     */
    public List<RelationCT> getRelation() {
        if (relation == null) {
            relation = new ArrayList<RelationCT>();
        }
        return this.relation;
    }

    /**
     * Gets the value of the coverage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coverage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoverage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoverageCT }
     * 
     * 
     */
    public List<CoverageCT> getCoverage() {
        if (coverage == null) {
            coverage = new ArrayList<CoverageCT>();
        }
        return this.coverage;
    }

    /**
     * Gets the value of the rights property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rights property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRights().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RightsCT }
     * 
     * 
     */
    public List<RightsCT> getRights() {
        if (rights == null) {
            rights = new ArrayList<RightsCT>();
        }
        return this.rights;
    }

    /**
     * Gets the value of the scope property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scope property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScope().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScopeCT }
     * 
     * 
     */
    public List<ScopeCT> getScope() {
        if (scope == null) {
            scope = new ArrayList<ScopeCT>();
        }
        return this.scope;
    }

    /**
     * Gets the value of the castList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the castList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCastList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CastListCT }
     * 
     * 
     */
    public List<CastListCT> getCastList() {
        if (castList == null) {
            castList = new ArrayList<CastListCT>();
        }
        return this.castList;
    }

    /**
     * Gets the value of the teiHeader property.
     * 
     * @return
     *     possible object is
     *     {@link TeiHeaderCT }
     *     
     */
    public TeiHeaderCT getTeiHeader() {
        return teiHeader;
    }

    /**
     * Sets the value of the teiHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeiHeaderCT }
     *     
     */
    public void setTeiHeader(TeiHeaderCT value) {
        this.teiHeader = value;
    }

    /**
     * Gets the value of the refSystem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the refSystem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRefSystem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RefSystemCT }
     * 
     * 
     */
    public List<RefSystemCT> getRefSystem() {
        if (refSystem == null) {
            refSystem = new ArrayList<RefSystemCT>();
        }
        return this.refSystem;
    }

    /**
     * Gets the value of the osisWork property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOsisWork() {
        return osisWork;
    }

    /**
     * Sets the value of the osisWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOsisWork(String value) {
        this.osisWork = value;
    }

    /**
     * Gets the value of the annotateRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotateRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotateRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAnnotateRef() {
        if (annotateRef == null) {
            annotateRef = new ArrayList<String>();
        }
        return this.annotateRef;
    }

    /**
     * Gets the value of the annotateWork property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnotateWork() {
        return annotateWork;
    }

    /**
     * Sets the value of the annotateWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnotateWork(String value) {
        this.annotateWork = value;
    }

    /**
     * Gets the value of the annotateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnotateType() {
        return annotateType;
    }

    /**
     * Sets the value of the annotateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnotateType(String value) {
        this.annotateType = value;
    }

    /**
     * Gets the value of the editions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the editions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEditions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEditions() {
        if (editions == null) {
            editions = new ArrayList<String>();
        }
        return this.editions;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the osisID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the osisID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOsisID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOsisID() {
        if (osisID == null) {
            osisID = new ArrayList<String>();
        }
        return this.osisID;
    }

    /**
     * Gets the value of the resp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResp() {
        return resp;
    }

    /**
     * Sets the value of the resp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResp(String value) {
        this.resp = value;
    }

    /**
     * Gets the value of the subType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubType() {
        return subType;
    }

    /**
     * Sets the value of the subType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubType(String value) {
        this.subType = value;
    }

    /**
     * Gets the value of the n property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getN() {
        return n;
    }

    /**
     * Sets the value of the n property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setN(String value) {
        this.n = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }

    /**
     * Gets the value of the script property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScript() {
        return script;
    }

    /**
     * Sets the value of the script property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScript(String value) {
        this.script = value;
    }

}
